### ISSUE TITLE
Jupyter notebooks not found

### ISSUE THREAD

**Issue by colinmolter** [nshaud/DeepNetsForEO#1]
Hello,
I am trying to use caffe to perform pointwise classification on earth image. apparently, this is what is done here. Following that tutorial: http://adilmoujahid.com/posts/2016/06/introduction-deep-learning-python-caffe/ , I understand how to use caffe to do label classification. the question is how to work with pointwise classification. I tought that maybe the notebooks mentioned here could help. Could you tell me where could I find the notebooks mentioned.

thank you
colin

**Comment by nshaud** [comment]
You're right, the notebooks weren't available. I committed the files to the repository, they are now in the `notebooks` folder. Please read the comments carefully if you want to use the code on your own data.
