### ISSUE TITLE
Possible color mapping error in convert_to_color

### ISSUE THREAD

**Issue by asheeshr** [nshaud/DeepNetsForEO#12]
In [convert_gt.py](https://github.com/nshaud/DeepNetsForEO/blob/master/notebooks/convert_gt.py), the mapping in `convert_from_color` has  

> (0, 0, 0): 0
> (0, 0, 0): 6

while `convert_to_color`, has the mapping 

> 0: (255, 255, 255)
> 6: (0, 0, 0)

One of these doesn't seem right. The label images seem to have rgb (255,255,255) for impervious surfaces, which should be getting mapped to 0 in `convert_from_color`. The script still appears to work correctly as the 2D array is zero initialized.

**Comment by nshaud** [comment]
Ah, shoot, nice catch. It should be fixed in the latest commit, thanks !
