### ISSUE TITLE
Using per-image mean instead of dataset mean

### ISSUE THREAD

**Issue by asheeshr** [nshaud/DeepNetsForEO#13]
How would the performance change if using per-image mean rather than dataset-mean for training? Would there be significant degradation in the results?

**Comment by asheeshr** [comment]
Also, is there a reason behind not performing histogram equalization on the dataset prior to training?

**Comment by nshaud** [comment]
I did not experiment with lots of different normalization strategies. If you use a more data-driven normalization, you should perhaps increase the window size to compensate. Tell me how this works for you ;)
