### ISSUE TITLE
ImportError: No module named _caffe

### ISSUE THREAD

**Issue by helxsz** [nshaud/DeepNetsForEO#15]
after the installation, I tried to run the inference_patches.py, an error "ImportError: No module named _caffe" occurred 

```
sys.path.insert(0,CAFFE_ROOT+"/python")
import caffe
```

I read some other notes with similar problems, which says _caffe.so should be in the /python folder after make pycaffe

I can find the libcaffe.so and libcaffe.so.1.0.0-rc4 in the /caffe/build/lib, but in the /python folder i could find any _caffe.so. to make _caffe.so as suggested by some other,  I  tried ' make pycaffe ' inside /python folder, but a   'no rule to make target pycaffe ' error occored

**Comment by nshaud** [comment]
Did you edit the `CAFFE_ROOT` variable in the `config.py` file ? It should point to the folder in which you installed Caffe.

**Comment by helxsz** [comment]
I found the problem is related to ubuntu 16.04 but now it works for 14.04. I still don't know what is the problem for 16.04.

**Comment by nshaud** [comment]
Great ! Do you mind explaining what was the problem and how you solved it in case someone else encounters the same bug ?

**Comment by helxsz** [comment]
Most reason is related to the installation of caffe in 16.04. In 16.04 python 3 and opencv 3.5 is used, therefore can cause the caffe fail to produce the _caffe.so in these cases.
