### ISSUE TITLE
Error when executing training.py

### ISSUE THREAD

**Issue by sivagamiramadass** [nshaud/DeepNetsForEO#19]
![error_window](https://user-images.githubusercontent.com/31002092/31271429-fed7e6ba-aa76-11e7-8997-b6f0eccba1de.png)
Dear nshaud first i would like to thank you for the code you gave us in github. I am trying to execute this code. i am facing some error when executing training.py. I have attached the screenshot of the error i got. Kindly go through and guide me in solving this issue. I thank you for the effort you have put in.

**Comment by nshaud** [comment]
See previous errors, you probably forgot to generate the LMDB databases.
