### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by oneOfThePeople** [nshaud/DeepNetsForEO#2]
hi,
my mission is to do building segmentation.
i want to ask what you think i should change in the code or my data for make it work

1. my data is rgb for now, its matter? if yes in what way?
2. if i will get dsm data you think its will improve the result?
3. you think to take as label distance like  the [Yuan 2016](https://arxiv.org/abs/1602.06564) improve the result? 

thanks alot for the great code

**Comment by nshaud** [comment]
Hi,

Thanks for your interest in our project ! 

1. Our code can deal with RGB data, no problem. As long as your input data is 3-channels (e.g. IRRG, RGB, IRGB ou anything else), you should be fine.
2. Yes, DSM data can improve the predictions as it gives information about the pixel's height, which is impossible to infer from the RGB data. However, mixing DSM and RGB is difficult. The litterature from the computer vision community about using RGB-D data with deep learning might help you on this matter.
3. I'm not familiar with the work from Yuan, but it might be worth a try !

**Comment by oneOfThePeople** [comment]
thank you  :)
