### ISSUE TITLE
fusenet training prototxt？

### ISSUE THREAD

**Issue by lixiang-ucas** [nshaud/DeepNetsForEO#21]
I have successfully trained you network using irrg images and got pretty good results. However , in your original paper, you use the IRRG tiles (8bit format) and we build 8bit composite images using the DSM, NDSM and NDVI. Can you share the training prototxt? Or is it the same as the 'potsdam_irrg_osm_fusenet'?

**Comment by nshaud** [comment]
It's basically the same as the potsdam_irrg_osm_fusenet.
