### ISSUE TITLE
training.py

### ISSUE THREAD

**Issue by HetSP07** [nshaud/DeepNetsForEO#23]
python training.py --niter 40000 --update 1000 --init vgg16weights.caffemodel --snapshot trained_network_weights/

I'm getting this error 
Caffe definition prototxt written in ./train_segnet.prototxt.
Saved network graph in ./net_figure.png.
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0427 12:48:27.036200 24162 io.cpp:36] Check failed: fd != -1 (-1 vs. -1) File not found: ./reference_models/solver.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

Any idea! thanks !

**Comment by nshaud** [comment]
You are using the old Caffe version of this code. I suggest moving to the newer PyTorch version if you can.

If you really want to stick with the Caffe code, it seems that it is not able to find  the solver file. You'd have to check why it isn't written in the right path.
