### ISSUE TITLE
Merge prediction result as GeoTIFF

### ISSUE THREAD

**Issue by firmanhadi** [nshaud/DeepNetsForEO#25]
Hi,

Thank you very much for sharing.
I am new to deep learning and Python but successfully setup the environment and
could produce the result.

Is it possible to merge prediction (classification) result as GeoTIFF?

Thanks.

Regards,

Firman.

**Comment by nshaud** [comment]
It is possible but outside the scope of this code. You have to use external tools to achieve this. You can use tools such as gdal or `geotifcp` to copy the geoinfo from the original image GeoTIFF to the predictions (both have the same raster dimensions, so this should be pretty easy).
