### ISSUE TITLE
prediction on my image

### ISSUE THREAD

**Issue by Averill-kk** [nshaud/DeepNetsForEO#26]
Hello,
I'm new to studying neural networks and Python. 
I have such a question, How can I upload my image to the network and how to make a prediction.
I also ported the i-python notebook to google colab. https://drive.google.com/open?id=1fnrPFHrdfKyG9JUTchaOMtXQnxzfqocj
Thank you for understanding.(sorry for my english)

**Comment by nshaud** [comment]
See here how to import data on Colab : https://colab.research.google.com/notebooks/io.ipynb
