### ISSUE TITLE
Typos to load Potsdam data

### ISSUE THREAD

**Issue by gaslen** [nshaud/DeepNetsForEO#27]
Hi, 
In the notebook, the parser to load the Potsdam data must be modified : 
Original :   all_ids = ["_".join(f.split('_')[3:5]) for f in all_files]
What works : all_ids =  ["_".join(f.split('_')[5:7]) for f in all_files] 

And there is a typo in DATA_FOLDER for Potsdam :  it begins with a "3" not with a "Y".

**Comment by salma26** [comment]
Good morning,
How did you manage to get the DataSet of Vahingen and Postdam ?
Did you contact the webmaster of ISPRS website ? 
thank you

**Comment by hurricane2018** [comment]
@gaslen  @nshaud 
 Why should it be 3_Ortho_IRRG , not 2_Ortho_RGB ?  I think we use use 2 instead of Y. Do you think so ?

**Comment by nshaud** [comment]
@hurricane2018 You can use either 3_Ortho_IRRG if you want to use the IRRG data or 2_Ortho_RGB if you want to use RGB. Either are valid choices.

The notebook has been updated to reflect this.

**Comment by akhilchibber1** [comment]
I see an Error while Loading the Dataset using the command "all_ids = ["".join(f.split('')[5:7]) for f in all_files]" which can be seen in the Screenshot. Can you please help me out with a fix for this?

![ERROR](https://user-images.githubusercontent.com/74544237/160388497-be54eee5-5d3c-41d3-9322-deef006e6ddd.jpg)
.
