### ISSUE TITLE
Won't pull in forked Caffe

### ISSUE THREAD

**Issue by PeterSprague** [nshaud/DeepNetsForEO#3]
$ git init
$ git submodule update
Cloning into '/......../DeepNetsForEO/caffe'...
error: no such remote ref ec4f1fff70b7e67a6f9ba31b6a22d685183ecf67
Fetched in submodule path 'caffe', but it did not contain ec4f1fff70b7e67a6f9ba31b6a22d685183ecf67. Direct fetching of that commit failed.

I have just directly git cloned your fork

**Comment by nshaud** [comment]
Thanks for pointing this out, there was an error in the submodule configuration.

You should be able to get everything working by doing :
```
git clone https://github.com/nshaud/DeepNetsForEO.git
git submodule init
git submodule update
```
I'll update the README.

**Comment by PeterSprague** [comment]
Thanks, pulled correctly.
