### ISSUE TITLE
Data set present in the link does not match the code

### ISSUE THREAD

**Issue by Kadivendi** [nshaud/DeepNetsForEO#32]
Hello sir, the data set present in the [https://drive.google.com/drive/folders/0B8XVGOkhuqDTdGNibWJPeTcxLVE](url) is not matching with the code.Please provide the exact dataset used for the code!

**Comment by nshaud** [comment]
The ISPRS datasets for Vaihingen and Potsdam are available here:

- Vaihingen http://www2.isprs.org/commissions/comm3/wg4/2d-sem-label-vaihingen.html
- Potsdam http://www2.isprs.org/commissions/comm3/wg4/2d-sem-label-potsdam.html

The Google Drive link you are referring to points to additional OpenStreetMap annotations in raster format. These are optional.
