### ISSUE TITLE
problems with SGDSolver

### ISSUE THREAD

**Issue by nicolaferrari96** [nshaud/DeepNetsForEO#34]
Hi, during the execution of training.py, I got this error:

> 
>  Traceback (most recent call last):
>   File "training.py", line 223, in <module>
>     solver = caffe.SGDSolver(SOLVER_FILE)
> RuntimeError: basic_string::_S_create

in config.py my SOLVER_FILE is 

> SOLVER_FILE = '../models/solver_isprs_vaihingen_irrg.prototxt'

Thanks

**Comment by nshaud** [comment]
The Caffe version is legacy code that is not supported anymore. If you still have problems with this code, I suggest that you move to the PyTorch version.
