### ISSUE TITLE
 nDSM DATA of  Vaihingen Dataset

### ISSUE THREAD

**Issue by hurricane2018** [nshaud/DeepNetsForEO#37]
Dear Dr. Audebert @nshaud :

    Thank you for your wonderful work "Beyond RGB: Very high resolution urban remote sensing with multimodal deep networks" [1]. However, I can't find the nDSM of Vaihingen Dataset. Could you provide it ? Thank you very much !
[1] Audebert, Nicolas, Bertrand Le Saux, and Sébastien Lefèvre. "Beyond RGB: Very high resolution urban remote sensing with multimodal deep networks." ISPRS Journal of Photogrammetry and Remote Sensing 140 (2018): 20-32.

Best,

**Comment by nshaud** [comment]
@hurricane2018 You closed the issue, I assume you found the dataset ? If so, do you mind uploading it somewhere so I can add a link in the README ?

**Comment by hurricane2018** [comment]
@nshaud Sure. 
1. Firstly, download the normalized DSM data from website :

https://www.researchgate.net/publication/270104315_Normalized_DSM_-_heights_encoded_in_dm_-_see_report_for_details

2. rename the file with zip.

**Comment by nshaud** [comment]
Thanks, I will update the README.
