### ISSUE TITLE
Docker build produces error

### ISSUE THREAD

**Issue by PeterSprague** [nshaud/DeepNetsForEO#4]
$ cd caffe/docker
$ docker build -t gei/caffe-eo:cpu standalone/cpu
### produces error:
------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named packaging.version
The command '/bin/sh -c git clone -b ${CLONE_TAG} --depth 1 https://github.com/BVLC/caffe.git . &&     for req in $(cat python/requirements.txt) pydot; do pip install $req; done &&     mkdir build && cd build &&     cmake -DCPU_ONLY=1 .. &&     make -j"$(nproc)"' returned a non-zero code: 1
  
$ docker run -i caffe-eo bash
$ cd /opt/caffe
$ ll
yields no build dir to run make runtest

using BVLC/caffe image => 
$ cd /opt/caffe/build
$ make runtest
...........
[100%] Built target runtest

**Comment by PeterSprague** [comment]
standalone/cpu Dockerfile is over a year behind in commits from BVLC/caffe master.  Uses Ubuntu 14, not 16.
copied newest cpu Dockerfile from BVLC/caffe -> EO/caffe/docker/standalone/cpu
$ docker build -t gei/caffe-eo:cpu standalone/cpu
$ docker run -i caffe-eo bash
$ cd /opt/caffe
$ make runtest
[----------] Global test environment tear-down
[==========] 1104 tests from 150 test cases ran. (136129 ms total)
[  PASSED  ] 1104 tests.
[100%] Built target runtest

Reviewed the two Dockerfiles, seemed compatible.  Would this make a difference with the fork?  

Can/should the upsample layer have a pull request to the BVLC/caffe master?  Problems?

**Comment by nshaud** [comment]
I'm not using Docker so I cannot guarantee that I can help you fix it. I updated the Caffe submodule to the latest master branch from Caffe upstream. Maybe this helps ?

There is already a PR for the [Upsample/Unpooling layer](https://github.com/BVLC/caffe/pull/3601) in the BVLC/caffe, although it has not been merged yet. When it is merged, I will consider switching to the official caffe repository.

**Comment by PeterSprague** [comment]
Thanks.
