### ISSUE TITLE
Initialization of V-fusenet

### ISSUE THREAD

**Issue by suntianren** [nshaud/DeepNetsForEO#42]
Hi, I'm very interested in your work. I have read your paper. It's very helpful.  And i wish to know more about your experiments details.  
Are the weights of the encoder in V-fusenet initialized with those of VGG-16 trained on ImageNet, or SegNet encoder trained on IRRG images and Composite images?

**Comment by nshaud** [comment]
If I recall correctly, in the paper we initialized it using pretrained SegNets on IRRG and composite but you can train it end-to-end starting from VGG-16, it's just longer to converge.

**Comment by suntianren** [comment]
Thanks a lot :)
