### ISSUE TITLE
downloading dataset

### ISSUE THREAD

**Issue by sundar19** [nshaud/DeepNetsForEO#43]
hi , 
this may be a bit silly but , I got an ftp link how to download the datasets from it?

**Comment by zhy788** [comment]
> hi ,
> this may be a bit silly but , I got an ftp link how to download the datasets from it?

xftp software may help you. you can link the server with input the ftp login name and password.

**Comment by sundar19** [comment]
thank you

**Comment by sundar19** [comment]
It would be very helpful if you can share me the datasets through a drive link or something else as the download in that method is very tedious and slow (Even though I have a fast internet connection)

**Comment by ziwenjie** [comment]
I have the same problem

**Comment by nshaud** [comment]
I'm not the publisher of the dataset. Use any FTP client such as FileZilla to download them. If you have trouble downloading the data, ask directly the organizers of the ISPRS Vaihingen/Potsdam benchmarks.
