### ISSUE TITLE
code for the fusion of DSM data and RGB image

### ISSUE THREAD

**Issue by soumyaghosal03** [nshaud/DeepNetsForEO#44]
Is it possible to share the code for the FuseNet technique of the paper which takes both the IRRGB images and the Lidar DSMs as input ?

**Comment by nshaud** [comment]
At the moment I don't have the FuseNet code (it was originally in Caffe). You can find a more recent implementation of the original FuseNet for RGB-D here: https://github.com/MehmetAygun/fusenet-pytorch
