### ISSUE TITLE
DSM, NDSM and NDVI Part

### ISSUE THREAD

**Issue by LyesSaadSaoud** [nshaud/DeepNetsForEO#46]
Hello

Please could you provide a little explanation of how to get the images from DSM, NDSM, and NDVI. 
We can get the nDSM from as you said: The nDSM for the Vaihingen dataset is available here (courtesy of Markus Gerke, see also his webpage). 

But from where we can get NDSM  and NDVI. 

Also, combining those images is the same as doing an RGB image. 

Many thanks

**Comment by nshaud** [comment]
The DSM is included with the original dataset. The nDSM is available through the Google Drive link from the README. The NDVI has to be manually computed from the IRRG image:  NDVI = (IR - Red)/(IR + Red). Then you indeed combine those 3 channels into one RGB image. You might have to normalize everything into [0, 1] to avoid clipping artifacts.
