### ISSUE TITLE
error during model training 

### ISSUE THREAD

**Issue by ZouhairBALLOUCH** [nshaud/DeepNetsForEO#47]
Hello Sir,
Please I would like to change the  ISPRS Postdam dataset by another one but I always receive this error in the training
Concerning the error, please refer to the attached screenshot
Thank you in advance for your help
Best regards
![screenshot](https://user-images.githubusercontent.com/62794017/112970768-77e27480-9146-11eb-86c4-b10ccff7a18b.JPG)

**Comment by nshaud** [comment]
Please include the full stack trace. I assume this is occurring when computing the accuracy in the test function? It would indicate that you don't have the same number of pixels in the images and the ground truth.

Since you changed the dataset, can you check that the images and ground truth masks have the same size?

**Comment by ZouhairBALLOUCH** [comment]
ok I will check the size  , Thank you very much

**Comment by ZouhairBALLOUCH** [comment]
I solved the size problem but I get this error 
![screen](https://user-images.githubusercontent.com/62794017/113006401-3b763f00-916d-11eb-83bb-b55c645941d4.JPG)

**Comment by nshaud** [comment]
Did you change the `test()` function? It should return either 3 values (if `all=True` or one).

**Comment by ZouhairBALLOUCH** [comment]
Hello Sir , I have not changed anything in the test() function   
![3](https://user-images.githubusercontent.com/62794017/113056847-3bddfc80-91a4-11eb-8ce3-9ef08f4ff58f.JPG)

**Comment by nshaud** [comment]
In the third line from the end, you commented the last value of the tuple. This is why there are not enough values to unpack. Closing this issue since this is not related to the notebook.

**Comment by ZouhairBALLOUCH** [comment]
Thank you very much
