### ISSUE TITLE
Solver file "solver_isprs_vaihingen_irrg.prototxt"

### ISSUE THREAD

**Issue by jorgenaya** [nshaud/DeepNetsForEO#7]
For me it has no sense that the solver "solver_isprs_vaihingen_irrg.prototxt" in the models folder point to the net with the same name.

The not should not be the "segnet_isprs_vaihingen_irrg.prototxt" file??

**Comment by nshaud** [comment]
Yep, you're right, this should be fixed with the latest commit.
