### ISSUE TITLE
Overfitting?

### ISSUE THREAD

**Issue by oneOfThePeople** [nshaud/DeepNetsForEO#8]
there is something strange in the result.
i train the net and then i run the inference.py script with top_mosaic_09cm_area1.tif
i see that in the gt of this image there is a little mistake and the problem is that in the prediction there is the same mistake.
i was thinking maybe there is a problem with my traning but your pre-trained model has the same result.

this is the gt:
![image](https://cloud.githubusercontent.com/assets/20380203/23408748/e4d538a0-fdd1-11e6-9598-5b16f596f9f3.png)

you see that the house is not full covered ?

and this is the  prediction:
![image](https://cloud.githubusercontent.com/assets/20380203/23408819/1c1011e6-fdd2-11e6-9ef9-208534ad4943.png)

what do you think?

**Comment by nshaud** [comment]
Two things :

1) On which tiles did you train your network ?

The pretrained IRRG network has been trained with the following split of the dataset : 
  * Training tiles : 1, 3, 5, 7, 11, 13, 15, 17, 21, 23, 26, 28, 30
  * Testing tiles  : 32, 34, 37

Therefore, it will strongly overfit on the tile 1, which should be expected for most deep networks. If you want to see "true" performance of the pre-trained network, try it on tiles 32, 34 or 37.

2) SegNet will probably overfit anyway on some weird details. For example, there are geometric distorsions in some images (e.g. along the edge of buildings) and SegNet will overfit on this. I'm not sure how to fight against this without any kind of spatial regularization.

**Comment by oneOfThePeople** [comment]
i use tile 1.
you think maybe with more data its will be less overfitting?
thanks

**Comment by nshaud** [comment]
Training on more tiles should decrease overfitting, yes. However, you should not evaluate your model on the same tiles that you used for training ! Evaluation should be performed on held out data that has not been seen during training. E.g., if you train on tiles 1,3,5,7,11,13, you should test on tiles 15, 17, 21, etc.
